name: 每4小时同步 GitHub 私有仓库 → Gitee
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 强制 Node.js 24，消除警告
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 同步到 Gitee
        run: |
          git config --global user.name "Sync"
          git config --global user.email "sync@github.com"
          
          # ========== 只改这里 ==========
          GITEE_USER="czrgitee"
          GITEE_REPO="OAS"
          # ==============================
          
          git remote add gitee https://${{ secrets.GITEE_TOKEN }}@gitee.com/${GITEE_USER}/${GITEE_REPO}.git
          git push -f --all gitee
